name: Run build pipeline

on:
  push:
    -branches:
      - "**"
      - "!pages"
  pull_request:
  workflow_dispatch:

env:
  # environment variables to config `turbo` to use the local cache server
  TURBO_API: "http://127.0.0.1:9080"
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "dinero"
  TURBO_REMOTE_ONLY: true
  # Used by scripts/build/types.js
  CI: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/build
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
